name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: [self-hosted, devops-lab]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests..."
